# -------------------------
# Persistent Volume (Global)
# -------------------------
apiVersion: v1
kind: PersistentVolume
metadata:
  name: flask-pv
  labels:
    type: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /srv/nfs/qus4            # <-- YOUR Miami ID
    server: 10.48.228.25
  persistentVolumeReclaimPolicy: Retain

---
# -------------------------
# Persistent Volume Claim (Global)
# -------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: nfs
